language: go

go: 
 - 1.3
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - 1.8
 - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
